
name: Build and Deploy to IKS

on:
  push:
    branches: [ "main" ]

jobs:
  prueba_1:
    runs-on: ubuntu-latest
    steps:
      - name : traer codigo
        uses: actions/checkout@v4
      - name : echo actual
        run : echo "hola mundo" 
      
